### ISSUE TITLE
KitchenAid compatibility

### ISSUE THREAD

**Issue by Tylersuard** [impressivewebs/HTML9-Responsive-Boilerstrap-js#179]
Hello.  I tried to install this on my KitchenAid toaster.  It did not work.  Should I try to cross-compile the mainframe first?

**Comment by joeytwiddle** [comment]
How can you expect help when you provide so little information? We don't get paid for this you know!

Which KitchenAid toaster model is it, the standard CrunchMaster or the new HyperCrisp?

Which version of ToastOS are you running? (To find this out, pinch the heating coils with your two favourite fingers and hold down the plunger for 3 minutes.)

You should have at least seen a popup. What shade was it?

Have you watched all six series of The Wire? How did you vote in your nation's last election? How do you feel about dolphins? Who will win next year's Wimbledon?

Please also provide your toaster's IP address, MAC address, your kitchen account ID, your citizen ID, the orientation of your toaster relative to both absolute north and magnetic north, and the 9th, 4th and 37th digits of your toaster's serial ID, so that we may assist you with this matter.

**Comment by CrossEye** [comment]
@joeytwiddle:

Come now, the 4th digit of the serial number is overkill.  Besides, it's easily derivable from the popup color and MAC address.  Please note that I'm not one of those pedants who like to point out there is a redundancy in kitchen account id, dolphin affinity score and both of the north readings; the calculations are arduous, and it's just as easy to ask for them all.  In other words, I'm reasonable about asking for possibly redundant information.

But really, there is simply no need to ask people to supply such privacy-revealing information when we've already been able to determine who @Tylersuard had a crush on at 13 (and why he's still afraid to talk about it to his friends), his breakfast menus since 1994 (I know, I know, except for that odd month in 2007 -- we're working on it!), and all the songs he sings in shower more than twice per year.

@Tylersuard: 

We do need the rest of that information, though.  And, please, for heaven's sake, don't try cross-compiling to the mainframe until you've read both volumes of the Safety Manual.

**Comment by Tylersuard** [comment]
I’m sorry for the late response, I own a porpoise and it needs to be bathed with a sponge periodically.

Upon further examination I found that my toaster is actually a Sunbeam, which I didn’t find in this repo’s list of compatible brands.  I will try re-installing and report back if there is an issue.

Thank you for your time.
