### ISSUE TITLE
Website is down! :cry: 

### ISSUE THREAD

**Issue by nomad-software** [impressivewebs/HTML9-Responsive-Boilerstrap-js#189]
How can I troll people now???

**Comment by CrossEye** [comment]
You can always troll people.

Always.

But as to the website, the system is designed so that it can never go down.  Its off-line mode is supercharged so that if you drop boiling oil all over your machine, your cat knocks your monitor out the window then gets out the car and runs it over, and a power outage sends you back to the dark ages, H9RB will work exactly as it did before.  We call this, "not just future-proof, but past-proof, present-proof, and even three-weeks-from-next-Thursday-proof".

Are you sure you don't simply have a typo?  Even cross-universal compatibility can't do useful spellchecking.

**Comment by nomad-software** [comment]
omg, you are right! It's back up! HTML9 Responsive Boilerstrap JS is the future!
