### ISSUE TITLE
You killed my frog. :(

### ISSUE THREAD

**Issue by jeremiah** [impressivewebs/HTML9-Responsive-Boilerstrap-js#34]

**Comment by CrossEye** [comment]
Why did you close this?

Was the frog resurrected?  Are frogs no longer part of the web ecosystem?  Have you lost heart?  Do you no longer love frogs?  Has the memory of the good times you had with your frog faded?  Have you found yourself a toad during the intervening years?

We can't abandon our amphibious friends just because it's been more than five years!
